Nodetool to get or modify guardrails configuration
Summary:
[cassandra-4.1-simulator-dtest]

Guardrails can only be modified through JMX, or in cassandra.yaml for persistent change.

This diff provides a general nodetool command to check the current guardrails setting and change the guardrails setting via JMX.

- Show all guardrails / Show enabled guardrails
- List all available setters for guardrails

Test Plan:
UT

Tested locally:

```
~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool getguardrailsconfig
Guardrails Configuration:
guardrails applied on supuerusers
        enabled: false

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool getguardrailsconfig --full
Guardrails Configuration:
guardrails applied on supuerusers
        enabled: false
total number of user keyspaces
        warning threshold(maximum): -1
        failing threashold(maximum): -1
total number of tables on user keyspaces
        warning threshold(maximum): -1
        failing threashold(maximum): -1
number of columns per table
        warning threshold(maximum): -1
        failing threashold(maximum): -1
number of secondary indexes per table
        warning threshold(maximum): -1
        failing threashold(maximum): -1
ability to create secondary indexes
        enabled: true
number of materialized views per table
        warning threshold(maximum): -1
        failing threashold(maximum): -1
usage of certain table properties
        warning values: null
        ignored values: null
        disallowed values: null
ability to use user-provided timestamps
        enabled: true
ability to use GROUP BY
        enabled: true
ability to use DROP and TRUNCATE TABLE
        enabled: true
ability to do bulk load
        enabled: true
ability to execute DDL statements
        enabled: true
ability to execute DCL statements
        enabled: true
ability to turn off compression
        enabled: true
ability to create new COMPACT STORAGE tables
        enabled: true
number of elements returned within page
        warning threshold(maximum): -1
        failing threashold(maximum): -1
number of partition keys in the IN clause
        warning threshold(maximum): -1
        failing threashold(maximum): -1
ability on operate lists that require read before write
        enabled: true
ability to execute statement with ALLOW FILTERING
        enabled: true
number of restrictions created by a cartesian product of a CQL's IN query
        warning threshold(maximum): -1
        failing threashold(maximum): -1
usage on read consistency levels
        warning values: null
        ignored values: null
        disallowed values: null
usage on write consistency levels
        warning values: null
        ignored values: null
        disallowed values: null
size of a collection
        warning threshold(maximum): null
        failing threashold(maximum): null
number of items of a collection
        warning threshold(maximum): -1
        failing threashold(maximum): -1
number of fields on each UDT
        warning threshold(maximum): -1
        failing threashold(maximum): -1
data disk usage percentage on the local node, used by a periodic task to calculate and propagate that status
        warning threshold(minimum): -1
        failing threashold(minimum): -1
number of minimum replication factor
        warning threshold(minimum): -1
        failing threashold(minimum): -1

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool setguardrailsconfig --list
setAllowFilteringEnabled        boolean
setBulkLoadEnabled      boolean
setCollectionSizeThreshold      [java.lang.String, java.lang.String]
setColumnsPerTableThreshold     [int, int]
setCompactTablesEnabled boolean
setDCLEnabled   boolean
setDDLEnabled   boolean
setDataDiskUsageMaxDiskSize     java.lang.String
setDataDiskUsagePercentageThreshold     [int, int]
setDropTruncateTableEnabled     boolean
setFieldsPerUDTThreshold        [int, int]
setGroupByEnabled       boolean
setGuardrailsOnSuperuserEnabled boolean
setInSelectCartesianProductThreshold    [int, int]
setItemsPerCollectionThreshold  [int, int]
setKeyspacesThreshold   [int, int]
setMaterializedViewsPerTableThreshold   [int, int]
setMinimumReplicationFactorThreshold    [int, int]
setPageSizeThreshold    [int, int]
setPartitionKeysInSelectThreshold       [int, int]
setReadBeforeWriteListOperationsEnabled boolean
setReadConsistencyLevelsDisallowed      java.util.Set
setReadConsistencyLevelsDisallowedCSV   java.lang.String
setReadConsistencyLevelsWarned  java.util.Set
setReadConsistencyLevelsWarnedCSV       java.lang.String
setSecondaryIndexesEnabled      boolean
setSecondaryIndexesPerTableThreshold    [int, int]
setTablePropertiesDisallowed    java.util.Set
setTablePropertiesDisallowedCSV java.lang.String
setTablePropertiesIgnored       java.util.Set
setTablePropertiesIgnoredCSV    java.lang.String
setTablePropertiesWarned        java.util.Set
setTablePropertiesWarnedCSV     java.lang.String
setTablesThreshold      [int, int]
setUncompressedTablesEnabled    boolean
setUserTimestampsEnabled        boolean
setWriteConsistencyLevelsDisallowed     java.util.Set
setWriteConsistencyLevelsDisallowedCSV  java.lang.String
setWriteConsistencyLevelsWarned java.util.Set
setWriteConsistencyLevelsWarnedCSV      java.lang.String

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool setguardrailsconfig setDCLEnabled false

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool getguardrailsconfig
Guardrails Configuration:
guardrails applied on supuerusers
        enabled: false
ability to execute DCL statements
        enabled: false

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool setguardrailsconfig setDDLEnabled false

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool getguardrailsconfig
Guardrails Configuration:
guardrails applied on supuerusers
        enabled: false
ability to execute DDL statements
        enabled: false
ability to execute DCL statements
        enabled: false

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/cqlsh
Connected to Test Cluster at 127.0.0.1:9042
[cqlsh 6.1.0 | Cassandra 4.1.3.0-SNAPSHOT | CQL spec 3.4.6 | Native protocol v5]
Use HELP for help.
cqlsh> create keyspace test4 with replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};
cqlsh> exit

~/Downloads/apache-cassandra-4.1.3.0 25s
❯ bin/nodetool setguardrailsconfig setGuardrailsOnSuperuserEnabled true

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/cqlsh
Connected to Test Cluster at 127.0.0.1:9042
[cqlsh 6.1.0 | Cassandra 4.1.3.0-SNAPSHOT | CQL spec 3.4.6 | Native protocol v5]
Use HELP for help.
cqlsh> create keyspace test3 with replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};
InvalidRequest: Error from server: code=2200 [Invalid query] message="Guardrail ddl_enabled violated: DDL statement is not allowed"
cqlsh> exit

~/Downloads/apache-cassandra-4.1.3.0 10s
❯ bin/nodetool setguardrailsconfig setDDLEnabled true

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool setguardrailsconfig setDCLEnabled true

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool getguardrailsconfig
Guardrails Configuration:
guardrails applied on supuerusers
        enabled: true

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool setguardrailsconfig setWriteConsistencyLevelsDisallowed  invalidInput
error: unsupported type: interface java.util.Set
-- StackTrace --
java.lang.IllegalArgumentException: unsupported type: interface java.util.Set
        at org.apache.cassandra.tools.nodetool.SetGuardrailsConfig.castType(SetGuardrailsConfig.java:146)
        at org.apache.cassandra.tools.nodetool.SetGuardrailsConfig.prepareArguments(SetGuardrailsConfig.java:118)
        at org.apache.cassandra.tools.nodetool.SetGuardrailsConfig.execute(SetGuardrailsConfig.java:105)
        at org.apache.cassandra.tools.NodeTool$NodeToolCmd.runInternal(NodeTool.java:400)
        at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:385)
        at org.apache.cassandra.tools.NodeTool.execute(NodeTool.java:288)
        at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:83)

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool setguardrailsconfig setWriteConsistencyLevelsDisallowedCSV  invalidInput
error: No enum constant org.apache.cassandra.db.ConsistencyLevel.INVALIDINPUT
-- StackTrace --
java.lang.IllegalArgumentException: No enum constant org.apache.cassandra.db.ConsistencyLevel.INVALIDINPUT
        at java.base/java.lang.Enum.valueOf(Enum.java:240)
        at org.apache.cassandra.db.ConsistencyLevel.valueOf(ConsistencyLevel.java:35)
        at org.apache.cassandra.db.ConsistencyLevel.fromString(ConsistencyLevel.java:88)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.apache.cassandra.db.guardrails.Guardrails.fromCSV(Guardrails.java:959)
        at org.apache.cassandra.db.guardrails.Guardrails.setWriteConsistencyLevelsDisallowedCSV(Guardrails.java:872)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:260)
        at java.management/com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
        at java.management/com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
        at java.management/com.sun.jmx.mbeanserver.MBeanIntrospector.invokeSetter(MBeanIntrospector.java:267)
        at java.management/com.sun.jmx.mbeanserver.PerInterface.setAttribute(PerInterface.java:102)
        at java.management/com.sun.jmx.mbeanserver.MBeanSupport.setAttribute(MBeanSupport.java:230)
        at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.setAttribute(DefaultMBeanServerInterceptor.java:736)
        at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.setAttribute(JmxMBeanServer.java:739)
        at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1489)
        at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
        at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
        at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.setAttribute(RMIConnectionImpl.java:720)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool setguardrailsconfig setWriteConsistencyLevelsDisallowedCSV  ONE

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool getguardrailsconfig
Guardrails Configuration:
guardrails applied on supuerusers
        enabled: true
usage on write consistency levels
        warning values: null
        ignored values: null
        disallowed values: ONE

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool setguardrailsconfig setWriteConsistencyLevelsDisallowedCSV  null

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool getguardrailsconfig
Guardrails Configuration:
guardrails applied on supuerusers
        enabled: true

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool setguardrailsconfig setWriteConsistencyLevelsDisallowedCSV  ONE,ANY

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool getguardrailsconfig
Guardrails Configuration:
guardrails applied on supuerusers
        enabled: true
usage on write consistency levels
        warning values: null
        ignored values: null
        disallowed values: ANY,ONE

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool setguardrailsconfig setWriteConsistencyLevelsDisallowedCSV  null

~/Downloads/apache-cassandra-4.1.3.0
❯ bin/nodetool getguardrailsconfig
Guardrails Configuration:
guardrails applied on supuerusers
        enabled: true

```

Reviewers: O2017 Cassandra Service, #ldap_cassandra-super-users, runtian

Reviewed By: O2017 Cassandra Service, #ldap_cassandra-super-users, runtian

JIRA Issues: SO-28726

Differential Revision: https://code.uberinternal.com/D13404621