CASSANDRA-17724: Remove commons-lang dependency during build runtime
`commons-lang` is not a runtime dependency and a `java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils`
exception is encountered during startup when hitting the codepath in `StartupClusterConnectivityChecker`.

This error is encountered very infrequently, but it has the potential of preventing the `CassandraDaemon` from starting up.

This commit will fail the build process when the `org.apache.commons.lang.*` namespace is used in the code. This will prevent
anyone from adding the `commons-lang` build runtime dependency that is not available during runtime.