Implement disk headroom safeguard for incremental repair
Summary:
Given that anti-compaction during incremental repair can cause very significant disk growth on multiple nodes within a cluster, we should introduce a safeguard which would prevent incremental repair from starting if the node does not have enough disk headroom.

This diff implements a safeguard that rejects an incoming incremental repair session if the node's disk usage is too high (over 80% by default).

Test Plan:
Built the changes and deployed them to a test instance.

**Test for sufficient headroom**
  - Set headroom requirement to 0 (will allow running IR even when the disk is full): https://odin.uberinternal.com/cadence/execution/odin-dca1/90019191-20af-415f-ba94-60d0f96d90be/afdb57f7-8f2b-4d0c-9d39-04a523c64a86
  - Restart all nodes
  - Run incremental repair:
```
[udocker@/ #]cat /var/lib/cassandra/conf/cassandra.yaml | grep incremental_repair_disk_headroom_reject_ratio
incremental_repair_disk_headroom_reject_ratio: 0
[udocker@/ #]nodetool repair
[2024-06-12 06:30:45,536] Starting repair command #1 (4cbeaa60-2885-11ef-8f25-cd4568ad60bb), repairing keyspace test with repair options (parallelism: parallel, primary range: false, incremental: true, job threads: 1, ColumnFamilies: [], dataCenters: [], hosts: [], previewKind: NONE, # of ranges: 48, pull repair: false, force repair: false, optimise streams: false, ignore unreplicated keyspaces: false, repairPaxos: true, paxosOnly: false)
     ...
[2024-06-12 06:30:45,826] Repair completed successfully
[2024-06-12 06:30:45,831] Repair command #1 finished in 0 seconds
[2024-06-12 06:30:45,837] condition satisfied queried for parent session status and discovered repair completed.
[2024-06-12 06:30:45,837] Repair completed successfully
```
  - Check participant logs to verify repair was completed successfully:
{F926516869}

**Test for insufficient headroom on repair coordinator**

  - Set headroom requirement to 1 on one node (will not run IR even with empty disk): https://odin.uberinternal.com/cadence/execution/odin-dca1/6cb7fb97-bc6c-47c2-b972-0f8da3d00ac2/1eff7c97-df60-4a04-a42b-2d261310f354
  - Restart the node
  - Start an IR session on the node and verify that it failed:
```
[udocker@/ #]cat /var/lib/cassandra/conf/cassandra.yaml | grep incremental_repair_disk_headroom_reject_ratio
incremental_repair_disk_headroom_reject_ratio: 1
[udocker@/ #]nodetool repair
[2024-06-11 23:59:02,870] Replication factor is 1. No repair is needed for keyspace 'system_auth'
[2024-06-11 23:59:02,883] Starting repair command #1 (407402b0-2889-11ef-8b14-5d121be3a02e), repairing keyspace system_traces with repair options (parallelism: parallel, primary range: false, incremental: true, job threads: 1, ColumnFamilies: [], dataCenters: [], hosts: [], previewKind: NONE, # of ranges: 2, pull repair: false, force repair: false, optimise streams: false, ignore unreplicated keyspaces: false, repairPaxos: true, paxosOnly: false)
[2024-06-11 23:59:02,905] Repair command #1 failed with error Rejecting incoming repair, disk usage above threshold
[2024-06-11 23:59:02,906] Repair command #1 finished with error
error: Repair job has failed with the error message: Repair command #1 failed with error Rejecting incoming repair, disk usage above threshold. Check the logs on the repair participants for further details
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: Repair command #1 failed with error Rejecting incoming repair, disk usage above threshold. Check the logs on the repair participants for further details
	at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:137)
	at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
	at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:633)
	at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:555)
	at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:474)
	at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor.lambda$execute$0(ClientNotifForwarder.java:108)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Test for insufficient headroom on repair participant**

  - Set headroom requirement to 1 on one node (will not run IR even with empty disk): https://odin.uberinternal.com/cadence/execution/odin-dca1/6cb7fb97-bc6c-47c2-b972-0f8da3d00ac2/1eff7c97-df60-4a04-a42b-2d261310f354
  - Restart the node
  - Start an IR session on a different node and verify that it failed:
```
[udocker@/ #]nodetool repair
[2024-06-12 06:39:18,574] Starting repair command #1 (7e8a0d40-2886-11ef-9923-35f054a392dd), repairing keyspace test with repair options (parallelism: parallel, primary range: false, incremental: true, job threads: 1, ColumnFamilies: [], dataCenters: [], hosts: [], previewKind: NONE, # of ranges: 48, pull repair: false, force repair: false, optimise streams: false, ignore unreplicated keyspaces: false, repairPaxos: true, paxosOnly: false)
[2024-06-12 06:39:18,636] Repair command #1 failed with error Got negative replies from endpoints [/10.90.115.54:28038]
[2024-06-12 06:39:18,643] Repair command #1 finished with error
error: Repair job has failed with the error message: Repair command #1 failed with error Got negative replies from endpoints [/10.90.115.54:28038]. Check the logs on the repair participants for further details
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: Repair command #1 failed with error Got negative replies from endpoints [/10.90.115.54:28038]. Check the logs on the repair participants for further details
	at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:137)
	at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
	at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:633)
	at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:555)
	at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:474)
	at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor.lambda$execute$0(ClientNotifForwarder.java:108)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Reviewers: O2017 Cassandra Service, #ldap_cassandra-super-users, runtian

Reviewed By: O2017 Cassandra Service, #ldap_cassandra-super-users, runtian

Subscribers: runtian

JIRA Issues: SO-30900

Differential Revision: https://code.uberinternal.com/D14093019