Implement v2 of autorepairstatus and runautorepaironce nodetool commands
Summary:
Currently the deprecation of the v1 auto-repair framework is blocked on the migration of dtests from v1 auto-repair to v2 auto-repair. However, the dtest migration itself is blocked as dtests make use of  `runautorepaironce` and `autorepairstatus` nodetool command to interact with the auto-repair framework. This means that in order to migrated dtests to auto-repair v2 (and in turn unblock the v1 deprecation), we need to improve the nodetool commands to support the v2 auto-repair framework as well.

This diff introduces the additional flags required for `runautorepaironce` and `autorepairstatus` to work with the v2 auto-repair framework.

Test Plan:
Unit tests + experiments on a test instance:

`autorepairstatus`:

```
[udocker@/ #]nodetool autorepairstatus --v2 -t full
Data center group Active repairs                                                            Acitve force repairs
ALL NODES         76a852cf-1333-476b-8861-e2250499b15b,ff7fdca7-dd2a-4475-907f-bfdf8186aee4 EMPTY
Total             76a852cf-1333-476b-8861-e2250499b15b,ff7fdca7-dd2a-4475-907f-bfdf8186aee4 EMPTY
```

`runautorepaironce` when repair type is disabled:

```
[udocker@/ #]nodetool runautorepaironce --v2 -t full 10000
error: Auto-repair is disabled for repair type full
-- StackTrace --
org.apache.cassandra.exceptions.ConfigurationException: Auto-repair is disabled for repair type full
	at org.apache.cassandra.repair.AutoRepairV2.repairAsync(AutoRepairV2.java:123)
	at org.apache.cassandra.service.AutoRepairService.runAutoRepairOnce(AutoRepairService.java:121)
```

`runautorepaironce` when repair type is enabled:

```
udocker@/ #]nodetool autorepairstatus --v2 -t full
Data center group Active repairs Acitve force repairs
ALL NODES         EMPTY          EMPTY
Total             EMPTY          EMPTY
[udocker@/ #]nodetool runautorepaironce --v2 -t full 10000
[udocker@/ #]nodetool autorepairstatus --v2 -t full
Data center group Active repairs Acitve force repairs
ALL NODES         EMPTY          ff7fdca7-dd2a-4475-907f-bfdf8186aee4
Total             EMPTY          ff7fdca7-dd2a-4475-907f-bfdf8186aee4

# After some time

[udocker@/ #]nodetool autorepairstatus --v2 -t full
Data center group Active repairs Acitve force repairs
ALL NODES         EMPTY          EMPTY
Total             EMPTY          EMPTY
```

Logs also show repair commands being scheduled:

{F972510717}

Reviewers: O2017 Cassandra Service, #ldap_cassandra-super-users, jchovati

Reviewed By: O2017 Cassandra Service, #ldap_cassandra-super-users, jchovati

Subscribers: jchovati

JIRA Issues: SO-29062

Differential Revision: https://code.uberinternal.com/D15130713